# Numpy实验指导
## 实验1：数组创建和操作
1. 创建一个一维数组和二维数组

In [ ]:
import numpy as np

# 创建一维数组
arr1 = np.array([1, 2, 3, 4, 5])

# 创建二维数组
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr1)
print(arr2)


预期结果

```
[1 2 3 4 5]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 ```

 2. 使用arange函数创建一个数组，并将其转化为二维数组

In [ ]:
import numpy as np

# 使用arange函数创建一个数组
arr = np.arange(12)

# 将一维数组转化为二维数组
arr = arr.reshape(4, 3)

print(arr)


预期结果

```
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

```

3. 生成一个包含随机数的一维数组，并计算其平均值和方差


In [ ]:
import numpy as np

# 生成包含随机数的一维数组
arr = np.random.rand(10)

# 计算平均值和方差
mean = np.mean(arr)
var = np.var(arr)

print(arr)
print("平均值：", mean)
print("方差：", var)

预期结果：

```
[0.3610056  0.38148111 0.12963377 0.23321336 0.08693451 0.27263291
 0.13458466 0.63090281 0.99839905 0.79797651]
平均值： 0.4013761288417168
方差： 0.0892393601583078
```

4. 创建一个包含0至9的一维数组，将其中的奇数变为负数

In [ ]:
import numpy as np

# 创建包含0至9的一维数组
arr = np.arange(10)

# 将其中的奇数变为负数
arr[arr % 2 == 1] = -arr[arr % 2 == 1]

print(arr)


预期结果:

```
[ 0 -1  2 -3  4 -5  6 -7  8 -9]

```

5. 计算两个一维数组的点积


In [ ]:
import numpy as np

# 创建两个一维数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 计算两个一维数组的点积
dot_product = np.dot(arr1, arr2)

print(dot_product)


预期结果:

```
32
```

6. 计算两个二维数组的矩阵积

In [ ]:
import numpy as np

# 创建两个一维数组
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 计算a和b的点积
dot_product = np.dot(a, b)

print("a: ", a)
print("b: ", b)
print("a·b = ", dot_product)


预期结果：

```
a: [1 2 3]
b: [4 5 6]
a·b = 32

```
